language: node_js
node_js:
- 11.12.0
script:
- yarn test
env:
  global:
  - CI=true
  - TRAVIS_SECURE_ENV_VARS=true
  - secure: QZc+MgPF43I3u09wZiREmtTMcaY46VXCOgiT6zPUOIHOptbx0C2oxO4FybPhTBXXC4BUN+Y4PX39YIWWJRULCKYmiTE/cyRHBjYuDHPQWar/Ut5Tut+t5XOrp4eE0TjIdtg/KdNoJc/7jh3SPsqZUHaFuVRostRRcCEP6XINGtoUKmi0yTs0Yhp7a+40+yaUbAONwuBOlVG5mVj4yWIqrCx8NjajvsmcHMz7E3OLiqE2NF8U2RO00Ha+aVGllqm1BbDayZYLAATDW9p0rLjqmZyfQuin2qDslki93ek6fUS5ehvbpVi5HDyAJwuenxzfkcW3Tw6Ex9cxG4wwqXVBvq+gn6gzF3iH6d97g3UmLfp9bQ9EXzsp8onSU2VhKTgp+lJAaKsV23XrBlDuRXwwWLJkABeae73ezai+uAf64Sm6C6XlZnITAEqjnHTMeJB2MuDQfUPNkENUfLRuK2WYHqcRscIbVhmoY3vsKc5V9aMA0mpbsf6gxUoZDfimT+X5eS0tcY9O7b7f2c0Gjf+Rp9B1GuaIkgwvIne/B623DPxGBXb0IgJb7J/mH0UNeTikDSs6W1alUsxZiGvkF8APl9PGpxE7gKvPrAZDSHfFV47A3gxYbjPKXWunKYOIsLZrUPEVIQPBE5ReB+uGZPz4sEpzzlpW24A4bJ3PdS+DXTI=
before_deploy:
- cd client && npm install netlify-cli -g && yarn build && cd ..
deploy:
  - provider: script
    script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./client/build --prod
    skip_cleanup: true
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: U2NU02N1vBuUMcRDTFBLrAMT0Fz6MFDcDua3f7cxrAOzV5k1BZhCxxzAC0rNe3mo4sDS+JVbS+KISbDDaNpPzo1RMRDvgwdhuzTj/Ww7wnx4lh2J2sVVp1bqEk+qhiRDuqeTTEVTpIPpw2w73TH9bFRA/hRvp9X/JF+ZXyonFneaM5Bmj8xaUEjtu9wiIvlbAKEKkJiUkrA8ovtvi4N2nTpxrp4YaqO+kcZJLAElsd1RgKq+6CmrFzQWEEX11syaDWAdj//vs0OfpCx06IN2O4kf91mUFunsHn3zJ7GpoDYei1nML+rTlSRP2zgd9WSLCOLrE7Yuyaf5tAbe174MDUtrd+fy0H/gg8HpUlckqpHxjVuE14+8FFE2F8V1v2XusUjerv+igz6xHNUTkkdnmHt+824zuxp1FInkSIBPq//Tj5nBU3yS6idLE9IiwRPxsyw/1cnYdf8W76X4YPNFBCofCBL5GhznHFobaKDP3BGQFbjhEr8zr9/g7JYR9JjOS00mpU0Ert/bO3ucsGZF1q/VK+tnXkjEol3fN256zA3oFlMYgfe+ebvASQpRtM3hBsvjkXcWaU68Ebq0Agp+Eg526mp4Je/o1kOx8PLGlZTPOHZJ7MplCz1oT6z4ahttZZaNAlX5cA3AJC93rU5/OUSSUvuB4+w7HaD5QDg3HkA=
    app: online-chess-batch-6
