language: node_js
node_js:
- 11.12.0
script:
  - yarn test
deploy:
  provider: heroku
  api_key:
    secure: YGDThG8y+gTJvrqVE88fSlhT4fMRaolYGHYTmZ7BCbJAuw/WCUbsLp807MAje36yzQ8V+kIsswF9tcz3bDXq/q8pS5ECDOIZ6dPYvw7qdwOXEhCD0Elp7v8X7DZyZmH1jT0WcBPlTZ9HyLv4nQXgs6Y7I0RtYXUXD3Z7EmXEUvvdEYVKqsfeASMK89+3lJoNY/5m421xwjWjo7BrpQpST+TYVVcqbyFg3Ls4dJo30JahifvnX9TbtekAWCOMVn3k6t039aHTjcMGPTBecNElknT0Ciex88ZqtRmIofO2E5Nx2Gymo+t9+VJv0XXH8nidmUa+pFo/x0AzoBUbultJQseKFoop54TfZvR00pThM9y0mWcrDPJ1itXG8LQuvfSSbpl+YQINb7Xim+9xMZkd2UvqFbU1uohQSisdT7dFZPblfTM3paTOWS8Wa0dGA8pUmv7DPAvDDw9ATtQR0nhFEqUiTardyuyzpfREXDRxlUjL8ZX6Zca8kdYAktF1dGIm6Iyso+axidvCg8fDx/6DVQheljFlQU7jnnMt9qy/m6nyIVA1UB4DHDX5qD19SZD0RiYVnuP+TFnipE/bggOyCiGlLvwbUus+k1mdtD66tuoA3GTU1g4/uwxIclfIagvRDuR9l9LygQdCg+DX+n/QWbsy3lIAcXxzfsQQq5XBjd4=
