language: node_js
node_js:
- 10.15.3
script:
- yarn test
env:
  global:
  - CI=true
  - TRAVIS_SECURE_ENV_VARS=true
  - secure: QZc+MgPF43I3u09wZiREmtTMcaY46VXCOgiT6zPUOIHOptbx0C2oxO4FybPhTBXXC4BUN+Y4PX39YIWWJRULCKYmiTE/cyRHBjYuDHPQWar/Ut5Tut+t5XOrp4eE0TjIdtg/KdNoJc/7jh3SPsqZUHaFuVRostRRcCEP6XINGtoUKmi0yTs0Yhp7a+40+yaUbAONwuBOlVG5mVj4yWIqrCx8NjajvsmcHMz7E3OLiqE2NF8U2RO00Ha+aVGllqm1BbDayZYLAATDW9p0rLjqmZyfQuin2qDslki93ek6fUS5ehvbpVi5HDyAJwuenxzfkcW3Tw6Ex9cxG4wwqXVBvq+gn6gzF3iH6d97g3UmLfp9bQ9EXzsp8onSU2VhKTgp+lJAaKsV23XrBlDuRXwwWLJkABeae73ezai+uAf64Sm6C6XlZnITAEqjnHTMeJB2MuDQfUPNkENUfLRuK2WYHqcRscIbVhmoY3vsKc5V9aMA0mpbsf6gxUoZDfimT+X5eS0tcY9O7b7f2c0Gjf+Rp9B1GuaIkgwvIne/B623DPxGBXb0IgJb7J/mH0UNeTikDSs6W1alUsxZiGvkF8APl9PGpxE7gKvPrAZDSHfFV47A3gxYbjPKXWunKYOIsLZrUPEVIQPBE5ReB+uGZPz4sEpzzlpW24A4bJ3PdS+DXTI=
before_deploy:
- cd client && npm install netlify-cli -g && yarn build && cd ..
deploy:
  - provider: script
    script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./client/build --prod
    skip_cleanup: true
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: lQ3pdPg3NgIZZXZbbDWzV3CUDH7Sa0OqfpopY6J2SJa23o8/HMKl45sjnG8bBbjT04w6cH+cOf6B3ZUTYHx0iV+pLd/SCMdSNf/V4F1+zNtKoEpOdqvHpmmpnBWezpB/P6sALE127UlfkNfIl4XUbw9Qm+nbvmodWCsIuNsrejIFdJ9/uE9LIzZDo7g29BQQFXqQ3iMpycGlzoWt+26V/oUtdNY9aovxi4Ddku8Q5b1SHQpQWEZq0VbPrb87UT5HQVaXbdPt70nD5XG1zuXftC6mlXvge2pq3+gCG+hYcYf/6VL+Oe6Qvrpet8BKyzIQijD23my0E3Qrm2asYqMpyMO9o5iT9UNiRhQmZxz0FSLOSHtfBZDbR+/qYiLiRf9JJvNd83l7lVnPMeUfuHQJD4gtb7UnL0CoFiz3XXjJ3DfvQG1ncE+ROLYq8nPhd2orStZVEGicHFefPmHdkYThLn/rUKvFlRBhEv686juZzhqdVDWxmLfaTSlB/5dwU7H8fPait98S/FNsATIN/NX6GsfOgEjRO2/Uf5zh2RT5z7jUoZhdX/OKq1IR3YWHLDD9Fa+lFA1XiThaOryGPfqHk/jdusL6yS4ghqm2sM4/i4d4MGrae6oAWDI1azHx6HpLgjb/Go0bjBfrZyPlACglRHp8BukRXKMBUg3Z4lVAsjE=
    app: online-chess-batch-6
